const $=s=>document.querySelector(s);
const records=[
{title:'把想法，做成空间',type:'实体模型 / 设计练习',img:'s42-2.jpg',gallery:['s42-2.jpg','s34-3.jpg'],text:'从图纸走向可触摸的空间。通过实体模型，观察体量、尺度与场地之间的关系，让想法在制作中逐渐清晰。',x:920,y:390,w:370,h:290},
{title:'从一张白纸开始',type:'空间构成 / 模型实验',img:'s35-2.jpg',gallery:['s35-2.jpg','s35-5.jpg'],text:'用纸板、线材与简单的构件，练习空间的组织。立体构成中的每一次搭接，都是对结构、秩序与光影的一次提问。',x:1370,y:150,w:250,h:300},
{title:'一起，把问题展开',type:'工作室日常 / 指导交流',img:'s17-3.jpg',gallery:['s17-3.jpg','s16-1.jpg'],text:'把设计带到桌面上，也把问题带到彼此面前。简维通过师生指导、同伴讨论与经验分享，让设计在交流中继续向前。',x:470,y:570,w:330,h:275},
{title:'线条里的建筑',type:'手绘 / 观察与表达',img:'s23-1.jpg',gallery:['s23-1.jpg','s41-3.jpg'],text:'从观察到落笔，用线条理解建筑。手绘记录空间的细节，也训练我们辨认比例、层次与光影的能力。',x:430,y:180,w:270,h:300},
{title:'数字工具，新的可能',type:'AIGC / 设计探索',img:'s43-2.jpg',gallery:['s43-2.jpg','s43-5.jpg','s18-2.jpg'],text:'把数字工具引入设计练习，探索不同的空间表达。工作室开展 AIGC 学习与交流，尝试将图像生成用于构思、比较和方案推敲。',note:'图像为设计探索与效果表达，非建成项目实景。',x:1740,y:470,w:330,h:295},
{title:'不止于工作桌',type:'伙伴 / 工作室生活',img:'s21-5.jpg',gallery:['s21-5.jpg','s04-2.jpg'],text:'设计之外，也有一起吃饭、聊天和分享生活的时间。工作室的日常，由每一位伙伴共同组成。',x:970,y:880,w:335,h:270},
{title:'工业智慧窗',type:'创新创业竞赛 / 产品设计',img:'s27-3.jpg',gallery:['s27-3.jpg'],text:'基于环境监测与 PLC 自动化控制的工业智慧窗。围绕环境感知与自动控制展开产品设计，探索建筑部件与数字技术结合的可能。',note:'创新创业竞赛方案。',x:90,y:920,w:310,h:260},
{title:'乡艺融创居',type:'乡村研究 / 竞赛方案',img:'s31-1.jpg',gallery:['s31-1.jpg'],text:'以装配式技术助力粤西农村住宅乡颜改造，围绕地方居住环境开展研究与设计探索。',note:'创新创业竞赛方案，非建成作品。',x:1550,y:960,w:340,h:260},
{title:'在制作中理解',type:'设备与实践 / 数字制作',img:'s15-1.jpg',gallery:['s15-1.jpg','s15-2.jpg'],text:'让数字世界与实体制作相遇。工作室的设备与实践资源，为模型制作、空间观察和技术学习提供支持。',x:100,y:430,w:240,h:270},
{title:'图纸中的耐心',type:'实践参与 / CAD 与天正',img:'s33-1.jpg',gallery:['s33-1.jpg'],text:'宣传资料收录了广铁老旧小区改造项目施工图相关工作。在图纸实践中，学习规范表达，理解设计信息如何准确传递。',note:'展示图纸相关工作，不代表工作室独立完成或建成该项目。',x:1880,y:90,w:300,h:260},
{title:'一处共同生长的地方',type:'学习空间 / 简维日常',img:'s14-1.jpg',gallery:['s14-1.jpg','s04-2.jpg'],text:'一张工作桌，也是一处相互学习的起点。简维工作室主要位于广东白云学院三立园负一层 U创长廊，欢迎对建筑与设计保持好奇的伙伴。',x:510,y:1060,w:300,h:255},
{title:'2026，与简维相遇',type:'秋季招新 / 加入我们',img:'recruitment-poster.jpg',join:true,x:1380,y:550,w:210,h:330},
{title:'一间正在发生的工作室',type:'学习空间 / 日常记录',img:'ppt-studio-01.jpg',gallery:['ppt-studio-01.jpg','ppt-studio-02.jpg'],text:'从一张桌子到一面作品墙，工作室的空间记录了成员的练习、讨论和共同完成的细节。',x:2500,y:120,w:360,h:250},
{title:'材料与设备',type:'数字制作 / 动手实践',img:'ppt-making-01.jpg',gallery:['ppt-making-01.jpg','ppt-making-02.jpg'],text:'模型制作让抽象的空间变得可以触摸。工作室成员在设备、材料和反复试作中理解尺度与构造。',x:1040,y:1430,w:360,h:260},
{title:'把问题带到桌面上',type:'工作坊 / 设计交流',img:'ppt-workshop-01.png',gallery:['ppt-workshop-01.png','ppt-workshop-02.jpg'],text:'围绕设计问题展开讨论，把图纸、电脑和模型放在同一张桌面上，寻找下一步的方向。',x:2180,y:1460,w:360,h:250},
{title:'一起吃饭，也一起长大',type:'伙伴 / 工作室生活',img:'ppt-life-01.jpg',gallery:['ppt-life-01.jpg','ppt-life-02.jpg','ppt-life-03.jpg'],text:'设计之外，伙伴们也在日常相处中建立联系。工作室的气氛由每一次见面、分享和互相帮忙组成。',x:3000,y:1270,w:370,h:250},
{title:'线条是另一种思考',type:'手绘 / 观察与表达',img:'ppt-sketch-01.jpg',gallery:['ppt-sketch-01.jpg'],text:'在纸面上观察建筑，从线条、明暗和比例开始，练习把看到的空间转化为自己的语言。',x:1700,y:650,w:300,h:330},
{title:'工业智慧窗',type:'创新创业竞赛 / 产品设计',img:'ppt-smart-window.png',gallery:['ppt-smart-window.png','ppt-bim.png'],text:'围绕环境感知与自动控制展开的产品设计练习，尝试让建筑部件回应使用者和环境。',note:'竞赛与研究方案，非建成项目。',x:2900,y:1870,w:360,h:250},
{title:'乡村空间研究',type:'乡村研究 / 竞赛方案',img:'ppt-rural-01.png',gallery:['ppt-rural-01.png','ppt-rural-02.png'],text:'从地方环境、材料和生活方式出发，记录乡村空间的现状，讨论更新与共生的可能。',note:'竞赛研究资料，非建成项目。',x:2000,y:980,w:360,h:250},
{title:'校园里的观察练习',type:'场地观察 / 建筑记录',img:'ppt-campus-01.jpg',gallery:['ppt-campus-01.jpg','ppt-campus-02.jpg'],text:'工作室的练习从身边开始。校园里的树、院落、走廊和教室，都是理解空间的第一现场。',x:650,y:1200,w:360,h:250},
{title:'从模型看空间',type:'实体模型 / 设计练习',img:'ppt-model-01.jpg',gallery:['ppt-model-01.jpg','ppt-model-02.jpg','ppt-model-03.jpg'],text:'通过不同材料和构成方式，练习体量、开口与路径，让设计在制作中逐步成形。',x:120,y:1850,w:360,h:280},
{title:'模型的尺度',type:'实体模型 / 构成实验',img:'ppt-model-04.jpg',gallery:['ppt-model-04.jpg','ppt-model-05.jpg','ppt-model-06.jpg'],text:'模型不只是结果，也是观察和推敲的工具。每一次切割、拼接和调整，都在重新确认空间关系。',x:2350,y:1650,w:350,h:270},
{title:'数字建模练习',type:'BIM / 数字表达',img:'ppt-bim.png',gallery:['ppt-bim.png'],text:'在数字环境中建立构件关系，练习从二维信息到三维空间的转换。',x:1200,y:200,w:360,h:250},
{title:'概念空间一',type:'概念表达 / 方案探索',img:'ppt-render-01.png',gallery:['ppt-render-01.png'],text:'以图像和模型推演空间氛围的概念练习，用于讨论形体、光线和材料的关系。',note:'概念表达图，非已建成建筑。',x:3300,y:220,w:260,h:260},
{title:'概念空间二',type:'概念表达 / 方案探索',img:'ppt-render-02.png',gallery:['ppt-render-02.png'],text:'通过不同的空间构图比较设计方向，记录从想法到方案的推演过程。',note:'概念表达图，非已建成建筑。',x:3300,y:600,w:260,h:260},
{title:'概念空间三',type:'概念表达 / 方案探索',img:'ppt-render-03.png',gallery:['ppt-render-03.png'],text:'建筑、景观与人的尺度在画面中交汇，作为设计讨论的视觉草图。',note:'概念表达图，非已建成建筑。',x:3350,y:1180,w:260,h:260},
{title:'概念空间四',type:'概念表达 / 方案探索',img:'ppt-render-04.png',gallery:['ppt-render-04.png'],text:'用光影和材料表达空间感受，探索数字工具在建筑构思中的辅助作用。',note:'概念表达图，非已建成建筑。',x:3100,y:1820,w:260,h:260},
{title:'学习桌上的日常',type:'学习空间 / 简维日常',img:'ppt-studio-04.png',gallery:['ppt-studio-04.png','ppt-studio-05.png'],text:'工作室也是一处安静学习的地方。图纸、模型和电脑并置在桌面上，设计从日常开始。',x:2700,y:80,w:360,h:160}
];
const world=$('#world'),viewport=$('#viewport'),dialog=$('#detail');let active=0,tx=0,ty=0,baseX=0,baseY=0,followX=0,followY=0,targetFollowX=0,targetFollowY=0,pointerX=0,pointerY=0,list=false,down=null,moved=false,lastFocus,raf=0,boardScale=1;const zoomScale=1.36;
records.forEach((r,i)=>{const b=document.createElement('button');b.className='tile';b.style.cssText=`left:${r.x}px;top:${r.y}px;width:${r.w}px;height:${r.h}px`;b.innerHTML=`<img src="assets/${r.img}" alt="${r.title}" draggable="false"><span class="tile-caption">${r.title}<small>${String(i+1).padStart(2,'0')}</small></span><span class="tile-type">${r.type}</span>`;b.onclick=()=>{if(!moved)r.join?showJoin():showRecord(i)};world.appendChild(b)});
world.insertAdjacentHTML('beforeend','<div class="world-note" data-x="870" data-y="170">在这里，<br>让想法生长。</div><div class="world-note" data-x="1110" data-y="1240">建筑之外，<br>也是生活。</div>');
function layoutWorld(){boardScale=Math.max(1,Math.min(1.35,viewport.clientWidth/1680));world.style.width=`${3800*boardScale}px`;world.style.height=`${2400*boardScale}px`;world.querySelectorAll('.tile').forEach((tile,i)=>{const r=records[i];tile.style.left=`${r.x*boardScale}px`;tile.style.top=`${r.y*boardScale}px`;tile.style.width=`${r.w*boardScale}px`;tile.style.height=`${r.h*boardScale}px`});world.querySelectorAll('.world-note').forEach(note=>{note.style.left=`${Number(note.dataset.x)*boardScale}px`;note.style.top=`${Number(note.dataset.y)*boardScale}px`})}
function transform(){world.style.transform=`translate3d(${tx}px,${ty}px,0) scale(${zoomScale})`}function clamp(){const minX=viewport.clientWidth-world.offsetWidth*zoomScale,minY=viewport.clientHeight-world.offsetHeight*zoomScale;tx=Math.min(120,Math.max(minX,tx));ty=Math.min(130,Math.max(minY,ty))}function movementBounds(){return{x:Math.max(0,world.offsetWidth*zoomScale-viewport.clientWidth)*.6,y:Math.max(0,world.offsetHeight*zoomScale-viewport.clientHeight)*.55}}function updateTileReveal(){if(list)return;const vr=viewport.getBoundingClientRect(),margin=150;world.querySelectorAll('.tile').forEach(tile=>{const r=tile.getBoundingClientRect(),dx=Math.max(vr.left-r.right,r.left-vr.right,0),dy=Math.max(vr.top-r.bottom,r.top-vr.bottom,0),distance=Math.hypot(dx,dy),reveal=Math.max(0,Math.min(1,distance?1-distance/margin:1));tile.style.setProperty('--reveal',reveal.toFixed(3));tile.classList.toggle('is-visible',reveal>0)})}function reset(){layoutWorld();baseX=viewport.clientWidth/2-(world.offsetWidth/2)*zoomScale;baseY=viewport.clientHeight/2-(world.offsetHeight/2)*zoomScale;followX=targetFollowX=0;followY=targetFollowY=0;pointerX=viewport.clientWidth/2;pointerY=viewport.clientHeight/2;tx=baseX;ty=baseY;clamp();transform();updateTileReveal()}
function explore(){ $('#home').hidden=true;$('#explore').hidden=false;$('#explore').classList.add('is-visible');reset();viewport.focus({preventScroll:true});history.replaceState(null,'','#explore')}
function home(){ $('#home').hidden=false;$('#explore').hidden=true;history.replaceState(null,'',location.pathname);window.scrollTo(0,0)}
$('.brand').onclick=e=>{e.preventDefault();home()};
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({explore,about:showAbout,join:showJoin})[b.dataset.action]());
if(location.hash==='#explore')explore();
function animateFollow(){raf=0;followX+=(targetFollowX-followX)*.085;followY+=(targetFollowY-followY)*.085;tx=baseX+followX;ty=baseY+followY;clamp();transform();updateTileReveal();if(Math.abs(targetFollowX-followX)>0.2||Math.abs(targetFollowY-followY)>0.2)raf=requestAnimationFrame(animateFollow)}
function followPointer(e){if(list||$('#explore').hidden||e.pointerType==='touch')return;const r=viewport.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;pointerX=e.clientX-r.left;pointerY=e.clientY-r.top;const bounds=movementBounds(),nx=(pointerX-r.width/2)/(r.width/2),ny=(pointerY-r.height/2)/(r.height/2);targetFollowX=-Math.max(-1,Math.min(1,nx))*bounds.x;targetFollowY=-Math.max(-1,Math.min(1,ny))*bounds.y;if(!raf)raf=requestAnimationFrame(animateFollow)}
viewport.addEventListener('pointermove',e=>{if(list)return;if(e.pointerType==='touch'){if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(dx,dy)>6){moved=true;viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId)}if(moved){tx=down.tx+dx;ty=down.ty+dy;clamp();transform();updateTileReveal()}}else followPointer(e)});
window.addEventListener('mousemove',followPointer);
viewport.addEventListener('pointerdown',e=>{if(list||e.pointerType!=='touch'||e.button!==0)return;down={x:e.clientX,y:e.clientY,tx,ty,id:e.pointerId};moved=false});
function release(){down=null;viewport.classList.remove('dragging');setTimeout(()=>moved=false,80)}viewport.addEventListener('pointerup',release);viewport.addEventListener('pointercancel',release);
viewport.addEventListener('keydown',e=>{if(list)return;const steps={ArrowLeft:[80,0],ArrowRight:[-80,0],ArrowUp:[0,80],ArrowDown:[0,-80]};if(steps[e.key]){e.preventDefault();tx+=steps[e.key][0];ty+=steps[e.key][1];clamp();transform()}});
world.addEventListener('focusin',e=>{if(list||!e.target.matches(':focus-visible'))return;const i=[...world.querySelectorAll('.tile')].indexOf(e.target);if(i<0)return;const r=records[i];baseX=viewport.clientWidth/2-(r.x+r.w/2)*zoomScale;baseY=viewport.clientHeight/2-(r.y+r.h/2)*zoomScale;followX=targetFollowX=0;tx=baseX;ty=baseY;clamp();transform()});
$('#reset').onclick=reset;$('#view-toggle').onclick=()=>{list=!list;$('#explore').classList.toggle('list',list);$('#view-toggle').textContent=list?'画布视图':'目录视图';$('#view-toggle').setAttribute('aria-pressed',String(list));$('#canvas-hint').textContent=list?'点击条目，阅读完整故事':'移动鼠标，发现更多 ↔';$('#reset').hidden=list;if(!list)reset()};window.addEventListener('resize',()=>{if(!$('#explore').hidden&&!list)reset()});
function open(content){if(!dialog.open)lastFocus=document.activeElement;$('#detail-content').innerHTML=content;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('.close').focus()}
function close(){dialog.close();lastFocus?.focus({preventScroll:true})}$('.close').onclick=close;dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
function showRecord(i){active=i;const r=records[i];open(`<article class="detail-inner"><p class="eyebrow">JIANWEI ARCHIVE / ${String(i+1).padStart(2,'0')}</p><h2 id="detail-title">${r.title}</h2><p class="detail-meta">${r.type}</p><p class="detail-text">${r.text}</p>${r.note?`<p class="detail-meta">${r.note}</p>`:''}<div class="detail-gallery">${r.gallery.map(im=>`<img src="assets/${im}" alt="${r.title} · 资料图" loading="lazy">`).join('')}</div><p class="detail-meta">图片来源：简维工作室 2026 秋季宣传资料</p><div class="detail-bottom"><button onclick="document.querySelector('.close').click()">返回探索</button><button id="next-record">下一个故事 ↗</button></div></article>`);$('#next-record').onclick=()=>{let n=(active+1)%records.length;records[n].join?showJoin():showRecord(n)}}
function showAbout(){open(`<article class="detail-inner"><p class="eyebrow">ABOUT JIANWEI</p><h2 id="detail-title">为共同的好奇，<br>留一个位置。</h2><p class="detail-text">简维工作室是广东白云学院的校内建筑设计工作室。我们围绕建筑设计、模型制作与数字技术展开学习和创作，通过竞赛、交流与实践，让设计离生活更近一步。</p><p class="detail-text">在这里，有经验的伙伴带着新成员一起学习。一个想法，可以从手绘开始，在模型里推敲，再在讨论中找到新的方向。</p><div class="about-grid"><section><h3>我们在做什么</h3><p>建筑设计与竞赛探索<br>实体模型与空间构成<br>BIM、AIGC 与数字表达<br>师生交流与同伴学习</p></section><section><h3>找到我们</h3><p>广东白云学院<br>三立园负一层 · U创长廊<br>挂靠公司：星舟建筑设计（广州）有限公司</p></section></div><div class="detail-gallery"><img src="assets/s04-2.jpg" alt="简维工作室伙伴合影"></div><div class="detail-bottom"><span>保持好奇，共同生长。</span><button id="about-join">加入简维 ↗</button></div></article>`);$('#about-join').onclick=showJoin}
function showJoin(){const expired=Date.now()>=Date.parse('2026-09-22T00:00:00+08:00');open(`<article class="detail-inner"><p class="eyebrow">2026 AUTUMN RECRUITMENT</p><h2 id="detail-title">下一段探索，<br>与你一起。</h2><p class="detail-text">欢迎建筑、规划、风景园林、土木等相关专业的大一、大二同学。带着学习热情与合作精神，在简维一起尝试、交流和成长。</p><div class="join-date">10.08 — 10.09</div><p class="detail-text">面试地点：致用楼 101<br>日常工作室：三立园负一层 U创长廊</p><p class="detail-meta">加入招新群，留意群内安排并参加面试。面试具体时段以群内通知为准。</p><div class="qr-grid"><section><h3>招新微信群</h3>${expired?'<p class="expired">本期群二维码已到期，请联系负责人获取最新入群方式。</p>':'<div class="qr-frame group"><img src="assets/recruitment-qr.png" alt="26 简维工作室秋季招新群二维码"></div><p>群二维码有效至 2026 年 9 月 22 日前。<br>若无法加入，请联系负责人。</p><a class="qr-full" href="assets/recruitment-qr.png" target="_blank" rel="noopener">查看 / 保存完整二维码 ↗</a>'}</section><section><h3>负责人微信</h3><div class="qr-frame manager"><img src="assets/manager-qr.png" alt="负责人微信高清二维码"></div><p>咨询工作室、面试与入群事宜。</p><a class="qr-full" href="assets/manager-qr.png" target="_blank" rel="noopener">查看 / 保存负责人高清二维码 ↗</a></section></div><div class="about-grid"><section><h3>一起学习</h3><p>共享学习空间，参与设计交流，<br>在模型制作与数字工具练习中积累经验。</p></section><section><h3>一起成长</h3><p>参与适合自己的竞赛与实践，<br>与工作室伙伴分享经验、相互支持。</p></section></div></article>`)}

